name: HiCFoundation
channels:
  - pytorch
  - nvidia
  - conda-forge
  - anaconda
  - bioconda
  - defaults
dependencies:
  - cudatoolkit=11.1.74
  - pip=21.1.3
  - python=3.8.10
  - pytorch=1.8.1
  - torchvision=0.9.1
  - timm=0.3.2
  - openjdk
  - pip:
      - easydict
      - opencv-python
      - simplejson
      - lvis
      - Pillow==9.5.0
      - pytorch_msssim
      - pandas
      - hic-straw
      - matplotlib
      - scikit-image
      - scipy
      - einops
      - tensorboard
      - cooler
      - numba
      - pyBigWig


